urls.py
from django.views.generic.base import RedirectView
from django.urls import path, reverse_lazy
from . import views

app_name = 'libtekin256'
urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy("libtekin256:article-list"))),
    path("article/create/", views.ArticleCreateView.as_view(), name="article-create"),
    path("article/update/<int:pk>/", views.ArticleUpdateView.as_view(), name="article-update"),
    path("article/<int:pk>/", views.ArticleDetailView.as_view(), name="article-detail"),
    path("article/delete/<int:pk>/", views.ArticleDeleteView.as_view(), name="article-delete"),
    path("articles/", views.ArticleListView.as_view(), name="article-list"),
    path("article/copy/<int:pk>/", views.ArticleCopyView.as_view(), name="article-copy"),
    path("article/filterstore/<int:from_store>/",views.ArticleListView.as_view(), name="article-filterstore"),
    path("rolecreate/", views.RoleCreateView.as_view(), name="role-create"),
    path("rolepopup/", views.RoleCreateView.as_view(), name="role-popup"),
    path("location/create/", views.LocationCreateView.as_view(), name="location-create"),
    path("location/update/<int:pk>/", views.LocationUpdateView.as_view(), name="location-update"),
    path("location/<int:pk>/", views.LocationDetailView.as_view(), name="location-detail"),
    path("location/delete/<int:pk>/", views.LocationDeleteView.as_view(), name="location-delete"),
    path("locations/", views.LocationListView.as_view(), name="location-list"),
    path("location/popup/", views.LocationCreateView.as_view(), name="location-popup"),
    path("model/create/", views.MamodelCreateView.as_view(), name="mamodel-create"),
    path("model/update/<int:pk>/", views.MamodelUpdateView.as_view(), name="mamodel-update"),
    path("model/<int:pk>/", views.MamodelDetailView.as_view(), name="mamodel-detail"),
    path("model/delete/<int:pk>/", views.MamodelDeleteView.as_view(), name="mamodel-delete"),   
    path("model/list/", views.MamodelListView.as_view(), name="mamodel-list"),
    path("model/popup/", views.MamodelCreateView.as_view(), name="mamodel-popup"),
    path("modelcategorycreate/", views.MamodelCategoryCreateView.as_view(), name="mamodelcategory-create"),
    # path("modelcategoryupdate/<int:pk>/", views.MamodelCategoryUpdateView.as_view(), name="mamodelcategory-update"),
    path("modelcategory<int:pk>/", views.MamodelCategoryDetailView.as_view(), name="mamodelcategory-detail"),
    # path("modelcategorydelete/<int:pk>/", views.MamodelCategoryDeleteView.as_view(), name="mamodelcategory-delete"),
    # path("modelcategorylist/", views.MamodelCategoryListView.as_view(), name="mamodelcategory-list"),
    path("modelcategorypopup/", views.MamodelCategoryCreateView.as_view(), name="mamodelcategory-popup"),
    path("articlenotestandardsubject/create/", views.ArticleNoteStandardSubjectCreateView.as_view(), name="articlenotestandardsubject-create"),
    path("articlenotestandardsubject/popup/", views.ArticleNoteStandardSubjectCreateView.as_view(), name="articlenotestandardsubject-popup")



]

models.py
from datetime import date
from django.utils import timezone
from django.db import  models
from django.conf import settings
from libstaff256.models import Entity
    
class ArticleStatus(models.Model):
    name = models.CharField("name", max_length=60, help_text="The name of this status")
    orderpos = models.IntegerField("list position", default=0, help_text="The position for default sorting")
    show = models.BooleanField("show by default", default=True, help_text = "If articles of this status should be shown by default")

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ("orderpos",)
    
class Location(models.Model):

    full_name = models.CharField("name", max_length=80, help_text="The full name of this location")
    abbreviation = models.CharField("abbreviation", max_length=10, blank=True, help_text="An abbreviation of the name")

    def __str__(self):
        return self.full_name

class MamodelCategory(models.Model):
        
    name = models.CharField("name", max_length=80, help_text="The name of this category for make/models")
    hide01 = models.BooleanField("hide customfield01", default=False, help_text="Hide custom field 01")
    hide02 = models.BooleanField("hide customfield02", default=False, help_text="Hide custom field 02")
    hide03 = models.BooleanField("hide customfield03", default=False, help_text="Hide custom field 03")
    hide04 = models.BooleanField("hide customfield04", default=False, help_text="Hide custom field 04")
    hide05 = models.BooleanField("hide customfield05", default=False, help_text="Hide custom field 05")
    hide06 = models.BooleanField("hide customfield06", default=False, help_text="Hide custom field 06")
    hide07 = models.BooleanField("hide customfield07", default=False, help_text="Hide custom field 07")
    hide08 = models.BooleanField("hide customfield08", default=False, help_text="Hide custom field 08")
    hide09 = models.BooleanField("hide customfield09", default=False, help_text="Hide custom field 09")
    hide10 = models.BooleanField("hide customfield10", default=False, help_text="Hide custom field 10")
    hide11 = models.BooleanField("hide customfield11", default=False, help_text="Hide custom field 11")
    hide12 = models.BooleanField("hide customfield12", default=False, help_text="Hide custom field 12")
    hide13 = models.BooleanField("hide customfield13", default=False, help_text="Hide custom field 13")
    hide14 = models.BooleanField("hide customfield14", default=False, help_text="Hide custom field 14")
    hide15 = models.BooleanField("hide customfield15", default=False, help_text="Hide custom field 15")
    hide16 = models.BooleanField("hide customfield16", default=False, help_text="Hide custom field 16")

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["name",]

class Mamodel(models.Model):

    def get_inventory_index_twin_choices():

        inventory_index_twin_choices=[
            ("common_name", "Common Name"),
        ]
        for fieldnum in range(1,17):
            fieldname=f'customfield{fieldnum:02}'
            try:
                fieldlabel = settings.LIBTEKIN["customfields"][fieldname]["label"]
                inventory_index_twin_choices.append((fieldname, fieldlabel))
            except KeyError:
                pass
            
        return inventory_index_twin_choices

    inventory_index_twin = models.CharField("Index field", choices=get_inventory_index_twin_choices, max_length=60, help_text="The article field to be mated with the inventory id.  Ex: If there is a Serial Number field and Serial Number is chosen, then this field and Serial Number will be kept identical")
    category = models.ForeignKey(MamodelCategory, null=True, blank=True, on_delete=models.SET_NULL, help_text="The category of this model")
    brand = models.CharField("Brand", blank=True, max_length=50, help_text="The brand name")
    name = models.CharField("Name",max_length=60, blank=True, help_text="The common name for the model")
    number = models.CharField("Model number",max_length=60, blank=True, help_text="The common name for the model")

    def __str__(self):
        name = self.name if self.name else self.number
        return '{} {}'.format(self.brand, name)
    

class Role(models.Model):

    name = models.CharField("name", max_length=60, help_text="The name of this role")

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["name",]

class Article(models.Model):

    inventory_index = models.CharField("index", unique=True, max_length=128)
    mamodel = models.ForeignKey(Mamodel, verbose_name="model", null=True, on_delete=models.SET_NULL, help_text="The make and model of this article")
    role = models.ForeignKey(Role, null=True, blank=True, on_delete=models.SET_NULL, help_text="The role of this article")
    status = models.ForeignKey(ArticleStatus, null=True, on_delete=models.SET_NULL, help_text="The status of this article")
    statusdate = models.DateField("status date", null=True, default=date.today, help_text="The date of the current status")
    inventorydate = models.DateField("inventory date", null=True, default=date.today, help_text="The date of the latest confirmation of possetion of this article")
    home_location = models.ForeignKey(Location, null=True, blank=True, on_delete=models.SET_NULL, related_name="home_articles", help_text="The home location of the article")
    assignee = models.ForeignKey(Entity, null=True, blank=True, on_delete=models.SET_NULL, related_name="assigned_articles", help_text="The person or organization to whom this article is assigned for use")
    responsible_party = models.ForeignKey(Entity, null=True, blank=True, on_delete=models.SET_NULL, related_name="responsible_for", help_text="The person or organization responsible for the condition and availability of this article")
    common_name = models.CharField("common name", max_length=60, blank=True, help_text="The common name, ex:\"Director's Laptop\", \"Meeting Room Projector\"")
    customfield01 = models.CharField("customfield 1", blank=True, max_length=128)
    customfield02 = models.CharField("customfield 2", blank=True, max_length=128)
    customfield03 = models.CharField("customfield 3", blank=True, max_length=128)
    customfield04 = models.CharField("customfield 4", blank=True, max_length=128)
    customfield05 = models.CharField("customfield 5", blank=True, max_length=128)
    customfield06 = models.CharField("customfield 6", blank=True, max_length=128)    
    customfield07 = models.CharField("customfield 7", blank=True, max_length=128)
    customfield08 = models.CharField("customfield 8", blank=True, max_length=128)
    customfield09 = models.CharField("customfield 9", blank=True, max_length=128)
    customfield10 = models.CharField("customfield 10", blank=True, max_length=128)
    customfield11 = models.CharField("customfield 11", blank=True, max_length=128)
    customfield12 = models.CharField("customfield 12", blank=True, max_length=128)    
    customfield13 = models.CharField("customfield 13", blank=True, max_length=128)    
    customfield14 = models.CharField("customfield 14", blank=True, max_length=128)    
    customfield15 = models.CharField("customfield 15", blank=True, max_length=128)    
    customfield16 = models.CharField("customfield 16", blank=True, max_length=128)    

    def __str__(self):

        return self.common_name if self.common_name > "" else self.inventory_index
    
    def get_label(self, customfieldname):
        labelfieldname = "label" + customfieldname[-2]
        return getattr(self.mamodel, labelfieldname)

    def get_field(self, label):
        if label in [
            "mamodel",
            "common_name",
            "role",
            "status",
        ]:
            return getattr(self, label)
        else:
            fields = settings.LIBTEKIN["customfields"]
            for key in fields:
                if fields[key]["label"] == label:
                    return getattr(self, key)

    def save(self, **kwargs):

        self.inventory_index = getattr(self,self.mamodel.inventory_index_twin )
        
        super().save(**kwargs)

        ArticleSnap.objects.create(
            article = self,
            inventory_index=self.inventory_index,
            mamodel=self.mamodel,
            role=self.role,
            common_name=self.common_name,
            status=self.status,
            statusdate=self.statusdate,
            inventorydate=self.inventorydate,
            home_location=self.home_location,
            assignee =self.assignee,
            responsible_party=self.responsible_party,
            customfield01=self.customfield01,
            customfield02=self.customfield02,
            customfield03=self.customfield03,
            customfield04=self.customfield04,
            customfield05=self.customfield05,
            customfield06=self.customfield06,
            customfield07=self.customfield07,
            customfield08=self.customfield08,
            customfield09=self.customfield09,
            customfield10=self.customfield10,
            customfield11=self.customfield11,
            customfield12=self.customfield12,
            customfield13=self.customfield13,
            customfield14=self.customfield14,
            customfield15=self.customfield15,
            customfield16=self.customfield16,
        )


    class Meta:

        ordering = ("mamodel", "common_name",)


class ArticleNoteStandardSubject(models.Model):
    subject_line = models.CharField("subject", max_length=63, help_text="The subject of the note")    
    last_used = models.DateTimeField("date/time", default=timezone.now, help_text="The date of the most recent note")

    def __str__(self):
        return self.subject_line

    class Meta:
        ordering=('last_used',)

class ArticleNote(models.Model):

    lead_note_limit_choices_to={"lead_note__isnull":True}

templates/libtekin256/_form.html
{% extends './_base.html' %}
{% load static %}
{% block content %}
{% endblock %}
{% block bottomscript %}
{{ block.super }}
{% endblock %}

templates/libtekin256/article_confirm_delete.html
{% extends './_base.html' %}

{% block content %}
    {% include './article_menu.html' %}
    <h2>{{ Article  }}</h2>
    <div class="detail" id="div_detail">
        {% include 'touglates/detail_field.html' with field=object.inventory_id  label=labels.article.inventory_id %}
        {% include 'touglates/detail_field.html' with field=object.mamodel  label=labels.article.mamodel %}
        {% include 'touglates/detail_field.html' with field=object.common_name  label=labels.article.common_name %}
        {% include 'touglates/detail_field.html' with field=object.category  label=labels.article.category %}
        {% include 'touglates/detail_field.html' with field=object.status  label=labels.article.status %}
        {% include 'touglates/detail_field.html' with field=object.statusdate  label=labels.article.statusdate %}
        {% include 'touglates/detail_field.html' with field=object.inventorydate  label=labels.article.inventorydate %}
        {% include 'touglates/detail_field.html' with field=object.home_location  label=labels.article.home_location %}
        {% include 'touglates/detail_field.html' with field=object.assignee  label=labels.article.assignee %}
        {% include 'touglates/detail_field.html' with field=object.customfield01  label=labels.article.customfield01 %}
        {% include 'touglates/detail_field.html' with field=object.customfield02  label=labels.article.customfield02 %}
        {% include 'touglates/detail_field.html' with field=object.customfield03  label=labels.article.customfield03 %}
        {% include 'touglates/detail_field.html' with field=object.customfield04  label=labels.article.customfield04 %}
        {% include 'touglates/detail_field.html' with field=object.customfield05  label=labels.article.customfield05 %}
        {% include 'touglates/detail_field.html' with field=object.customfield06  label=labels.article.customfield06 %}
        {% include 'touglates/detail_field.html' with field=object.customfield07  label=labels.article.customfield07 %}
        {% include 'touglates/detail_field.html' with field=object.customfield08  label=labels.article.customfield08 %}
        {% include 'touglates/detail_field.html' with field=object.customfield09  label=labels.article.customfield09 %}
        {% include 'touglates/detail_field.html' with field=object.customfield10  label=labels.article.customfield10 %}
        {% include 'touglates/detail_field.html' with field=object.customfield11  label=labels.article.customfield11 %}
        {% include 'touglates/detail_field.html' with field=object.customfield12  label=labels.article.customfield12 %}
        {% include 'touglates/detail_field.html' with field=object.customfield13  label=labels.article.customfield13 %}
        {% include 'touglates/detail_field.html' with field=object.customfield14  label=labels.article.customfield14 %}
        {% include 'touglates/detail_field.html' with field=object.customfield15  label=labels.article.customfield15 %}
        {% include 'touglates/detail_field.html' with field=object.customfield16  label=labels.article.customfield16 %}

        <form method="POST">
            {% csrf_token %}
            {% include 'touglates/form_field.html' with field="<button type='submit'>Delete</button>"  label_tag="Confirm Delete" %}            
        </form>

    {% include './article_menu.html' %}

{% endblock %}
{% block bottomscript %}
{{ block.super }}
{% endblock %}

templates/libtekin256/article_detail.html
{% extends './_base.html' %}

{% block content %}
    {% include './article_menu.html' %}
    <h2>{{ Article  }}</h2>
    <div class="detail" id="div_detail">
        {% include 'touglates/detail_field.html' with field=object.inventory_id  label=labels.article.inventory_id %}
        {% include 'touglates/detail_field.html' with field=object.mamodel  label=labels.article.mamodel %}
        {% include 'touglates/detail_field.html' with field=object.common_name  label=labels.article.common_name %}
        {% include 'touglates/detail_field.html' with field=object.category  label=labels.article.category %}
        {% include 'touglates/detail_field.html' with field=object.status  label=labels.article.status %}
        {% include 'touglates/detail_field.html' with field=object.statusdate  label=labels.article.statusdate %}
        {% include 'touglates/detail_field.html' with field=object.inventorydate  label=labels.article.inventorydate %}
        {% include 'touglates/detail_field.html' with field=object.home_location  label=labels.article.home_location %}
        {% include 'touglates/detail_field.html' with field=object.assignee  label=labels.article.assignee %}
        {% include 'touglates/detail_field.html' with field=object.customfield01  label=labels.article.customfield01 %}
        {% include 'touglates/detail_field.html' with field=object.customfield02  label=labels.article.customfield02 %}
        {% include 'touglates/detail_field.html' with field=object.customfield03  label=labels.article.customfield03 %}
        {% include 'touglates/detail_field.html' with field=object.customfield04  label=labels.article.customfield04 %}
        {% include 'touglates/detail_field.html' with field=object.customfield05  label=labels.article.customfield05 %}
        {% include 'touglates/detail_field.html' with field=object.customfield06  label=labels.article.customfield06 %}
        {% include 'touglates/detail_field.html' with field=object.customfield07  label=labels.article.customfield07 %}
        {% include 'touglates/detail_field.html' with field=object.customfield08  label=labels.article.customfield08 %}
        {% include 'touglates/detail_field.html' with field=object.customfield09  label=labels.article.customfield09 %}
        {% include 'touglates/detail_field.html' with field=object.customfield10  label=labels.article.customfield10 %}
        {% include 'touglates/detail_field.html' with field=object.customfield11  label=labels.article.customfield11 %}
        {% include 'touglates/detail_field.html' with field=object.customfield12  label=labels.article.customfield12 %}
        {% include 'touglates/detail_field.html' with field=object.customfield13  label=labels.article.customfield13 %}
        {% include 'touglates/detail_field.html' with field=object.customfield14  label=labels.article.customfield14 %}
        {% include 'touglates/detail_field.html' with field=object.customfield15  label=labels.article.customfield15 %}
        {% include 'touglates/detail_field.html' with field=object.customfield16  label=labels.article.customfield16 %}

        <h2>Links</h2>
        {% for articlelink in object.articlelink_set.all %}
            {% include 'touglates/detail_fields.html' with label="Link" field_1_label=labels.articlelink.name|add:": " field_1=articlelink.name %}
            {% include 'touglates/detail_fields.html' with field_1_label=labels.articlelink.url|add:": "  field_1="<a href='"|add:articlelink.url|add:"'>"|add:articlelink.url|add:"</a>"|safe %}
        {% endfor %}

        <h2>Notes</h2>
        {% for note in object.articlenote_set.all %} 
            {% include 'touglates/detail_fields.html' with label="Note" field_1=note.when %}
			{% include 'touglates/detail_fields.html' with label="subject" field_1=note.get_subject %}
        {% endfor %}
    </div>
    {% if copybutton %}
        <form action="{% url 'libtekin256:article-copy' object.pk %}" method="POST">
            {% csrf_token %}
            {% include 'touglates/form_field.html' with field="<button type='submit'>Copy</button>"  label_tag="Confirm Copy" %}            
        </form>
    {% endif %}
    {% include './article_menu.html' %}

{% endblock %}
{% block bottomscript %}
{{ block.super }}
{% endblock %}

templates/libtekin256/article_list.html
{% extends './_base.html' %}

{% block content %}
  {% include './article_menu.html' %}
  {% comment %} filter form {% endcomment %}
  <div id = "div_search_form">
    <form id="frm_filter" method="POST">
      {% csrf_token %}
      <table>
        {{ filter.form.as_table }}
        {{ filterstore_save.as_table }}
        <tr><td>Submit Search</td><td><button type="submit">Search</button></td></tr>
      </table>
    </form>
    <form method="GET" action="{% url 'libtekin256:article-list' %}">
      <table>
        {{ filterstore_retrieve.as_table }}
        <tr><td>Get Saved Filter</td><td><button type="submit" id="btn_retrieve">Retrieve</button></td></tr>
        <script>
          function toggleRetrieve() {
            var button = document.getElementById("btn_retrieve")
            var select = document.getElementById("{{ filterstore_retrieve.from_store.id_for_label }}")
            button.disabled = !(select.value > "")
            button.style.display = button.disabled ? "none" : ""
          }
          document.getElementById("{{ filterstore_retrieve.from_store.id_for_label }}").addEventListener("change", function() {
            toggleRetrieve()
          })
          toggleRetrieve()
        </script>
      </table>
    </form>
  </div>
  <div>
    <a id="a_showhideSearchForm" href="#"></a>
  </div>
  <script>
    function showhideSearchForm() {
      var div_searchForm = document.getElementById("div_search_form")
      if(div_searchForm.style.display=="none") {
        div_searchForm.style.display="block"
        a_showhideSearchForm.innerText="Hide Search Form"
      } else {
        div_searchForm.style.display="none"
        a_showhideSearchForm.innerText="Show Search Form"
      }
    }
    var a_showhideSearchForm = document.getElementById("a_showhideSearchForm")
    a_showhideSearchForm.addEventListener("click", function(e) {
      e.preventDefault()
      showhideSearchForm()
    })
    showhideSearchForm()
  </script>

  <h2>Articles</h2>
  <div class="list" id="div_detail">
    <table>
      <tr>
        <th></th>
        <th>{{ labels.article.inventory_id }}</th>
        <th>{{ labels.article.mamodel }}</th>
        <th>{{ labels.article.common_name }}</th>
        <th>{{ labels.article.category }}</th>
        <th>{{ labels.article.status }}</th>
        <th>{{ labels.article.statusdate }}</th>
        <th>{{ labels.article.inventorydate }}</th>
        <th>{{ labels.article.home_location }}</th>
        <th>{{ labels.article.assignee }}</th>
        <th>{{ labels.article.customfield01 }}</th>
        <th>{{ labels.article.customfield02 }}</th>
        <th>{{ labels.article.customfield03 }}</th>
        <th>{{ labels.article.customfield04 }}</th>
        <th>{{ labels.article.customfield05 }}</th>
        <th>{{ labels.article.customfield06 }}</th>
        <th>{{ labels.article.customfield07 }}</th>
        <th>{{ labels.article.customfield08 }}</th>
        <th>{{ labels.article.customfield09 }}</th>
        <th>{{ labels.article.customfield10 }}</th>
        <th>{{ labels.article.customfield11 }}</th>
        <th>{{ labels.article.customfield12 }}</th>
        <th>{{ labels.article.customfield13 }}</th>
        <th>{{ labels.article.customfield14 }}</th>
        <th>{{ labels.article.customfield15 }}</th>
        <th>{{ labels.article.customfield16 }}</th>

      </tr>
      {% for object in filter.qs %}
        <tr>
          <td><a href="{% url 'libtekin256:article-detail' object.pk %}">view</a></td>
          <td>{{ object.inventory_id }}</td>
          <td>{{ object.mamodel }}</td>
          <td>{{ object.common_name }}</td>
          <td>{{ object.category }}</td>
          <td>{{ object.status }}</td>
          <td>{{ object.statusdate }}</td>
          <td>{{ object.inventorydate }}</td>
          <td>{{ object.home_location }}</td>
          <td>{{ object.assignee }}</td>
          <td>{{ object.customfield01 }}</td>
          <td>{{ object.customfield02 }}</td>
          <td>{{ object.customfield03 }}</td>
          <td>{{ object.customfield04 }}</td>
          <td>{{ object.customfield05 }}</td>
          <td>{{ object.customfield06 }}</td>
          <td>{{ object.customfield07 }}</td>
          <td>{{ object.customfield08 }}</td>
          <td>{{ object.customfield09 }}</td>
          <td>{{ object.customfield10 }}</td>
          <td>{{ object.customfield11 }}</td>
          <td>{{ object.customfield12 }}</td>
          <td>{{ object.customfield13 }}</td>
          <td>{{ object.customfield14 }}</td>
          <td>{{ object.customfield15 }}</td>
          <td>{{ object.customfield16 }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
  {% include './article_menu.html' %}

{% endblock %}
{% block bottomscript %}
{{ block.super }}
{% endblock %}

templates/libtekin256/article_menu.html
<div class="menu app-menu">

  <div class="menu object-menu">

    {% if perms.add_article %}
      {% if 'article-create' == request.resolver_match.url_name %}
        <div class="menu-article menu-list menu-here">
            Add New
        </div>
      {% else %}
        <div class="menu-article menu-create">
          <a href="{% url 'libtekin256:article-create' %}">Add New</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.view_article %}
      {% if 'article-list' == request.resolver_match.url_name %}
        <div class="menu-article menu-list menu-here">
            List
        </div>
      {% else %}
        <div class="menu-article menu-list">
          <a href="{% url 'libtekin256:article-list' %}">List</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.view_article %}
      {% if 'article-detail' == request.resolver_match.url_name %}
        <div class="menu-article menu-detail menu-here">
            View
        </div>
      {% elif object.pk %}
        <div class="menu-article menu-detail">
          <a href="{% url 'libtekin256:article-detail' object.pk %}">View</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.add_article %}
      {% if 'article-copy' == request.resolver_match.url_name %}
        <div class="menu-article menu-detail menu-here">
            Copy
        </div>
      {% elif object.pk %}
        <div class="menu-article menu-copy">
          <a href="{% url 'libtekin256:article-copy' object.pk %}">Copy</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.change_article %}
      {% if 'article-update' == request.resolver_match.url_name %}
        <div class="menu-article menu-update menu-here">
          Edit
        </div>
      {% elif object.pk %}
        <div class="menu-article menu-update">
          <a href="{% url 'libtekin256:article-update' object.pk %}">Edit</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.delete_article %}
      {% if 'article-delete' == request.resolver_match.url_name %}
        <div class="menu-article menu-delete menu-here">
          Delete
        </div>
      {% elif object.pk %}
        <div class="menu-article menu-delete">
          <a href="{% url 'libtekin256:article-delete' object.pk %}">Delete</a>
        </div>
      {% endif %}
    {% endif %}

  </div>

</div>

templates/libtekin256/articlecategory_menu.html
<div class="menu app-menu">

  <div class="menu object-menu">

    {% if perms.add_role %}
      {% if 'role-create' == request.resolver_match.url_name %}
        <div class="menu-role menu-list menu-here">
            Add New
        </div>
      {% else %}
        <div class="menu-role menu-create">
          <a href="{% url 'libtekin256:role-create' %}">Add New</a>
        </div>
      {% endif %}
    {% endif %}

    {% comment %}
    {% if perms.view_role %}
      {% if 'role-list' == request.resolver_match.url_name %}
        <div class="menu-role menu-list menu-here">
            List
        </div>
      {% else %}
        <div class="menu-role menu-list">
          <a href="{% url 'libtekin:role-list' %}">List</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.view_role %}
      {% if 'role-detail' == request.resolver_match.url_name %}
        <div class="menu-role menu-detail menu-here">
            View
        </div>
      {% elif object.pk %}
        <div class="menu-role menu-detail">
          <a href="{% url 'libtekin:role-detail' object.pk %}">View</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.add_role %}
      {% if 'role-copy' == request.resolver_match.url_name %}
        <div class="menu-role menu-detail menu-here">
            Copy
        </div>
      {% elif object.pk %}
        <div class="menu-role menu-copy">
          <a href="{% url 'libtekin:role-copy' object.pk %}">Copy</a>
        </div>
      {% endif %}
    {% endif %}


    {% if perms.change_role %}
      {% if 'role-update' == request.resolver_match.url_name %}
        <div class="menu-role menu-update menu-here">
          Edit
        </div>
      {% elif object.pk %}
        <div class="menu-role menu-update">
          <a href="{% url 'libtekin:role-update' object.pk %}">Edit</a>
        </div>
      {% endif %}
    {% endif %}

    {% if perms.delete_role %}
      {% if 'role-delete' == request.resolver_match.url_name %}
        <div class="menu-role menu-delete menu-here">
          Delete
        </div>
      {% elif object.pk %}
        <div class="menu-role menu-delete">
          <a href="{% url 'libtekin:role-delete' object.pk %}">Delete</a>
        </div>
      {% endif %}
    {% endif %}

  {% endcomment %}

  </div>

</div>

templates/libtekin256/location_list.html
{% extends './_base.html' %}

{% block content %}
    {% include './location_menu.html' %}

    <h2>Locations</h2>
    <div class="list" id="div_detail">
        <table>
            <tr>
                <th></th>
                <th>{{ labels.location.full_name }}</th>
                <th>{{ labels.location.abbreviation }}</th>

            </tr>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url 'libtekin256:location-detail' object.pk %}">view</a></td>
                    <td>{{ object.full_name }}</td>
                    <td>{{ object.abbreviation }}</td>
                </tr>
        {% endfor %}
        </table>
    </div>
    {% include './location_menu.html' %}

{% endblock %}
{% block bottomscript %}
{{ block.super }}
{% endblock %}